[workspace.package]
version = "0.0.1-pre"
edition = "2024"
publish = false
rust-version = "1.88"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace]
resolver = "3"
members = [
  "crates/app",
  "crates/base",
  "crates/collections",
  "crates/store",
  "crates/x/*",
]

[workspace.dependencies]
copper-base = { path = "./crates/base" }
copper-collections = { path = "./crates/collections" }
copper-facet-account = { path = "./crates/x/account" }
copper-facet-bank = { path = "./crates/x/bank" }
copper-store = { path = "./crates/store" }

anyhow = "1"
borsh = "1.5"
bytes = "1"
iavl = { git = "https://github.com/inicio-labs/iavl.git", tag = "v0.1.0-alpha.2" }
nebz = "0.2.1"
serde = "1"
sha2 = "0.10"
thiserror = "2"
