[package]
name = "copper-base"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["bytes"] }
bytes = { workspace = true }
ed25519-dalek = "2.2"
sha2 = "0.10"
